// Products
export const SET_ERROR='SET_ERROR';
export const CLEAR_ERROR='CLEAR_ERROR';
export const FETCH_PRODUCTS='FETCH_PRODUCTS';
export const SET_LOADING_PRODUCTS='SET_LOADING_PRODUCTS';
export const INITIALIZE_PRODUCTS='INITIALIZE_PRODUCTS';

// Dialog
export const SHOW_DIALOG='SHOW_DIALOG';
export const HIDE_DIALOG='HIDE_DIALOG';

// Snackbar
export const SHOW_SNACKBAR='SHOW_SNACKBAR';
export const HIDE_SNACKBAR='HIDE_SNACKBAR';

// Shopping
export const ADD_TO_CART='ADD_TO_CART';
export const UPDATE_CART='UPDATE_CART';
export const DELETE_FROM_CART='DELETE_FROM_CART';
export const SET_HAS_CHECKED_OUT='SET_HAS_CHECKED_OUT';

// Auth
export const SET_LOADING='SET_LOADING';
export const SET_LOGIN_ERROR='SET_LOGIN_ERROR';
export const SET_TOKEN='SET_TOKEN';
export const LOGOUT_USER='LOGOUT_USER';

// Checkout
export const SET_ACTIVE_STEP='SET_ACTIVE_STEP';
export const UPDATE_BILLING_FIELD='UPDATE_BILLING_FIELD';
export const SET_VALIDITY='SET_VALIDITY';